### ISSUE TITLE
A few warnings and errors when running importCATS and calibrateCATS scripts

### ISSUE THREAD

**Issue by morganjmartin** [wgough/CATS-Methods-Materials#1]
Hey Guys!
We calibrated our CATS tags for the first time on 12/14 this week and I am trying to run your Matlab scripts to import the calibration data and run the calibration script. I think everything essentially worked fine, minus a couple of warnings and errors. I'm attaching screenshots of the errors I received at different steps. The main errors appear to be in the calibrateCATS script at cell 4 - errors which do not plot the legends in the figure and also a save error in cell 5 which is related to the .mat output file it saves. After running cell 5, it did create a new mat file named 'CATScal2.mat'. I'm just not certain if everything saved to that mat file properly due to the error I received. Please see the screenshots attached and let me know if this doesn't make sense. 

Also, I was prompted to use the NOAA website to calculate nT for my location in Victoria, Canada. I wasn't sure which value from the NOAA table to enter. I selected the 'Total' value on the far righthand side of the table. My value was 53,442.1 nT  which I entered as 53442.1 in the Matlab command window. Please let me know if you think that is the correct value to enter. 

One last thing - we used the tag positions 1-6 described in the bench test template for when we ran our tags on the record player. My gyroscope output figure in Matlab looks like yours in the wiki but with the steps 1-6 in a different order. I am pretty certain that we did it correctly based on the written instructions for tag positioning in the bench test template. Can you please ease my mind based on the screenshot I attached that I have done this properly? 
Copied from bench template spreadsheet:
Position 1 = positive   x: on end front up (Camera to the sky-rotate clockwise around x, negative   roll)
Position 2 = negative x: on front end   facing down  (camera towards the   ground)
Position 3 = positive y: on left side   camera facing forward
Position 4 = negative y: on right side,   camera facing forward, rotate up around y, positive pitch
Position 5 =  positive z: on back, camera facing forward
Position 6 = negative z: standard   position- flat with camera facing forward (rotate counter clockwise around z,   positive yaw)

Cheers for now, thank you and Merry Christmas!
Morgan Martin 
![Screenshot (684)](https://user-images.githubusercontent.com/33809841/102409830-51dcfe00-3fb5-11eb-89c3-93a3cf4dc3cf.png)
![Screenshot (678)](https://user-images.githubusercontent.com/33809841/102409832-52759480-3fb5-11eb-999f-ed77dea31cd8.png)
![Screenshot (679)](https://user-images.githubusercontent.com/33809841/102409834-530e2b00-3fb5-11eb-8ff6-96779cce5dba.png)
![Screenshot (680)](https://user-images.githubusercontent.com/33809841/102409836-53a6c180-3fb5-11eb-8297-2a15f0e82ff5.png)
![Screenshot (681)](https://user-images.githubusercontent.com/33809841/102409840-53a6c180-3fb5-11eb-878f-24f17759908a.png)
![Screenshot (682)](https://user-images.githubusercontent.com/33809841/102409841-543f5800-3fb5-11eb-99fd-770b46914fff.png)
![Screenshot (683)](https://user-images.githubusercontent.com/33809841/102409843-543f5800-3fb5-11eb-8ba1-09015e53b2b2.png)

**Comment by cadede** [comment]
Thanks, Morgan!  Yes, there was an error in the legend script which cued the other errors.  Thanks for catching, the updated script should have fixed the problem!  Your gyro cals look good, perhaps the tag was a bit wobbly on the turntable which gives the wobbly upper line, but the average value should still be usable, no need to redo.
